name: app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter    
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  provider: ^6.0.5
  shared_preferences: ^2.0.16
  http: ^0.13.5
  get_it: ^7.2.0
  device_info_plus: ^8.0.0
  intl: ^0.18.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  faker: ^2.1.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/ca/
    - assets/fonts/